---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: targylyen-app
  name: targylyen-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targylyen-app
  template:
    metadata:
      labels:
        app: targylyen-app
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources:
          requests:
            memory: 64Mi
            cpu: 5m   
      - command:
        - "/bin/sleep"
        - "infinity"
        image: busybox
        name: busybox
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
---
