---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: targylyen-nginx
  name: targylyen-nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targylyen-nginx
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: targylyen-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
---